[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rust_social = "CxwiJ8KMSqrM9JsddTvLT8AECQTXY87poSvd3f4YXhwN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

#[test.validator]
#bind_address="0.0.0.0"
#url = "https://mainnet.helius-rpc.com/?api-key=a23e14a3-7b17-4a47-939d-0474aeaa2432"
#ledger=".anchor/test-ledger"
#rpc_port=8899

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/mpl_token_metadata.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

api = "yarn run ts-node app/index.ts"
